name: ci

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8
            -
                name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN}}

            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/python-ci:latest
